---
title: "20210309-W11-Bechdel Test"
author: "CPXOPZ"
date: "2021/3/10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(colorspace)
```

```{r dat}
# Either ISO-8601 date or year/week works!

tuesdata <- tidytuesdayR::tt_load('2021-03-09')
tuesdata <- tidytuesdayR::tt_load(2021, week = 11)

bechdel <- tuesdata$bechdel
movies <- tuesdata$movies

# Or read in the data manually

raw_bechdel <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-09/raw_bechdel.csv')
movies <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-09/movies.csv')

```

```{r}
# # geom_bar
# movies %>% 
#   count(year, clean_test) %>% 
#   ggplot()+
#   geom_bar(aes(year, n, fill = clean_test), stat = "identity")

movies %>% 
  count(year, clean_test) %>% 
  mutate(clean_test = factor(clean_test, levels = c("men","nowomen","notalk", "dubious", "ok"),
                             labels = c("Men", "Nowomen","Notalk","Dubious", "Ok"),
                             ordered = T)) %>%
  ggplot()+
  geom_col(aes(year, n, fill = clean_test), position = "fill")+
  scale_x_continuous(breaks = c(seq(1970, 2013, 5), 2013))+
  scale_y_continuous(labels = scales::percent_format(), name = NULL)+
  scale_fill_discrete_diverging(palette = "Blue-Red",
                                name = "Test results",
                                # labels = c()
                                )+
  labs(title = "Bechdel Test Over Time",
       # subtitle = "",
       x = NULL,
       caption = "@CPXOPZ")+
  theme_minimal()+
  theme(legend.position = "bottom",
        plot.title = element_text(size = 23,
                                  face = "bold",
                                  hjust = 0.5))

ggsave(here::here("2021/20210309-W11-Bechdel Test", "20210309-W11-Bechdel_Test.png"),
       height = 15,
       width = 20,
       units = "cm",
       dpi = "retina",
       type = "cairo")
```

 