---
title: "20210406-W15-Global deforestation"
author: "CPXOPZ"
date: "2021/4/6"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-04-06

```{r package}
library(dplyr)
library(ggplot2)
library(gghighlight)
library(patchwork)
```

```{r data}
# tuesdata <- tidytuesdayR::tt_load('2021-04-06')
# tuesdata <- tidytuesdayR::tt_load(2021, week = 15)
# 
# forest_change <- tuesdata$forest_change

# Or read in the data manually

forest <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-06/forest.csv')
forest_area <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-06/forest_area.csv')
brazil_loss <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-06/brazil_loss.csv')
soybean_use <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-06/soybean_use.csv')
vegetable_oil <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-06/vegetable_oil.csv')

```

```{r datapre}
forest_area %>% 
  distinct(entity)

forest %>% 
  distinct(entity)
soybean_use %>% 
  distinct(entity)

vegetable_oil %>% 
  distinct(entity)
```

```{r shiny plot}
forPLot <- forest %>% 
  ggplot(aes(year, net_forest_conversion, group = entity, color = entity))+
  geom_line(size = 2,show.legend = F)+
  gghighlight(entity == "China",
              unhighlighted_params = list(size = 0.5))+
  scale_y_continuous(labels = scales::comma_format())+
  labs(title = "Change every 5 years for forest area in conversion",
       x = "Year",
       y = "Net forest conversion in hectares")+
  theme_light()

areaPlot <- forest_area %>% 
  ggplot(aes(year, forest_area, group = entity, color = entity))+
  geom_line(size = 2,show.legend = F)+
  gghighlight(entity == "China",
              unhighlighted_params = list(size = 0.5))+
  labs(title = "Forest area as a percent of global forest area",
       x = "Year",
       y = "Percent of global forest area")+
  theme_light()
  
```

```{r}
forPLot / areaPlot+
  plot_annotation(title = "Deforestation in China",
                  caption = "@CPXOPZ",
                  theme = theme(plot.title = element_text(size = 23, hjust = 0.5,
                                                          face = "bold",
                                                          margin = margin(10,5,10,5),
                                                          family = "Times")))

ggsave(here::here("2021/20210406-W15-Global deforestation","20210406-W15-Global_deforestation.png"),
       width = 6,
       height = 7,
       units = "in",
       dpi = 320,
       type = "cairo")

```

