---
title: "20220201-W05-Dog breeds"
author: "CPXOPZ"
date: "2022/2/1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r in}
tuesdata <- tidytuesdayR::tt_load('2022-02-01')
tuesdata <- tidytuesdayR::tt_load(2022, week = 5)

breed_traits <- tuesdata$breed_traits

# Or read in the data manually

breed_traits <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/breed_traits.csv')
trait_description <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/trait_description.csv')
breed_rank_all <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/breed_rank_all.csv')

```

```{r out}
folder_name <- "20220201-W05-Dog breeds"
data_name <- names(tuesdata)

for (i in seq_along(data_name)) {
  write.csv(tuesdata[[i]],here::here(paste0("2022/", folder_name),paste0(data_name[i],".csv")), row.names = F, na = "")
}
```

