---
title: "20201222-W52-Big Mac Index"
author: "CPXOPZ"
date: "2020/12/22"
output: html_document
editor_options: 
  chunk_output_type: console
---

[Data](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-12-22)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r package, message=FALSE}
library(dplyr)
library(ggplot2)
library(ggtext)
library(gganimate)
```

```{r data, message=FALSE}
bigmac <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-12-22/big-mac.csv')

# tuesdata <- tidytuesdayR::tt_load('2020-12-22')
# tuesdata <- tidytuesdayR::tt_load(2020, week = 52)
# 
# bigmac <- tuesdata$`big-mac`
```

具有日期变量date 2000-2007
国家名name
Big Mac prices are from McDonald’s 
exchange rates
GDP and population data used to calculate the euro area averages 
GDP per person data

```{r data pre}
skimr::skim(bigmac)
bigmac %>% 
  count(name, sort = T)

plot <- bigmac %>% 
  filter(name == "China") %>% 
  arrange(date) %>% 
  ggplot()+
  geom_line(aes(date, dollar_price))+
  geom_line(aes(date, dollar_ex))+
  scale_y_continuous(labels = scales::dollar_format())+
  labs(x = NULL,
       y = NULL,
       title = "**Trend over time**",
       subtitle = "*Local currency units per dollar* (Above) and *Price of a Big Mac* in dollars (Under)",
       caption = "*@CPXOPZ*")+
  theme_minimal()+
  theme(plot.title = element_markdown(),
        plot.subtitle = element_markdown(),
        plot.caption = element_markdown())+
  transition_reveal(date)


ani <- animate(plot, height = 10, width = 18, units = "cm", res = 150)
anim_save("20201222-W52-Big_Mac_Index.gif", ani)
```

***

```{r session}
sessionInfo()
```