---
title: "20201215-W51-Ninja Warrior"
author: "CPXOPZ"
date: "2020/12/15"
output:
  html_document:
    theme: paper
    highlight: kate
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, fig.showtext = T, fig.retina = 1)
```

```{r prep, message=FALSE}
library(dplyr)
library(stringr)
library(ggplot2)
library(RColorBrewer)
library(cowplot)
library(patchwork)
```

```{r data, message=FALSE}
ninja_warrior <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-12-15/ninja_warrior.csv')
```

```{r data-prep}
skimr::skim(ninja_warrior)

# 10seasons 28cities

races <- ninja_warrior %>% 
  select(season, location, round_stage) %>% 
  distinct() %>% 
  mutate(location = case_when(
    str_detect(location, "Sasuke") ~ "Sasuke",
    str_detect(location, "San Pedro") ~ "San Pedro",
    TRUE ~ location),
    index = row_number())

obstacle<- ninja_warrior %>% 
  group_by(season, round_stage) %>% 
  # count() %>% 
  mutate(round_stage = factor(round_stage, levels = c("Qualifying (Regional/City)","Finals (Regional/City)","Qualifying","Semi-Finals","National Finals - Stage 1","National Finals - Stage 2","National Finals - Stage 3","National Finals - Stage 4"), ordered = T))

```

```{r plots}
city_color <- colorRampPalette(brewer.pal(12,"Dark2"))(28)

race_plot <- ggplot(races) +
  geom_bar(aes(season, 1, group = index, fill = location), stat = 'identity', color = "white", size = 1.5)+
  scale_x_continuous(breaks = seq(1,10), labels = seq(1,10))+
  scale_fill_manual(values = city_color,
                    guide = guide_legend(title = "Cities",
                                         title.position = "bottom",
                                         title.hjust = 0.5,
                                         direction = "horizontal", nrow = 4))+
  labs(x = "Seasons",
       y = NULL,
       title = "Distribution of Ninja Warrior competitions")+
  theme_minimal()+
  theme(legend.position = "bottom")

round_plot <- ggplot(obstacle)+
  geom_bar(aes(round_stage,1, fill = as.factor(season)), stat = 'identity')+
  coord_flip()+
  scale_x_discrete(limits = rev(levels(obstacle$round_stage)))+
  scale_fill_manual(values = brewer.pal(10,"Spectral"),
                    guide = guide_legend("Season",
                                         nrow = 1))+
  labs(x = NULL,
       y = NULL,
       title = "Round distribution",
       caption = "@CPXOPZ")+
  theme_minimal()+
  theme(legend.position = "bottom",
        legend.spacing.x = unit(0, "pt"),
        legend.key.width = unit(90, "pt"))

race_plot/round_plot+
  plot_annotation(title = "Ninja Warrior",
                  theme = theme(plot.title = element_text(face = "bold",
                                                          hjust = 0.5,
                                                          size = 23)))

ggsave(here::here("2020/20201215-W51-Ninja Warrior", "20201215_W51_Ninja_Warrior.png"),
       width = 24,
       height = 24,
       units = "cm",
       type = ragg::agg_png(),
       dpi = "retina")
```

***

```{r session}
sessionInfo()
```