---
title: "20210119-W04-Kenya Census"
author: "CPXOPZ"
date: "2021/1/19"
output: 
  html_document:
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-01-19

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyr)
library(forcats)
library(ggplot2)
library(patchwork)
```

```{r data}
tt <- tidytuesdayR::tt_load('2021-01-19')

gender <- tt$gender
crops <- tt$crops
households <- tt$households

```

```{r prepare}
skimr::skim(households)
# 具体省份是否可以用地图展示？



```

```{r plot}
sub_dis <- crops %>% 
  rowwise() %>% 
  mutate(total = sum(across(where(is.numeric)), na.rm = T)) %>% 
  ungroup() %>% 
  select(SubCounty, total) %>% 
  mutate(SubCounty = as.factor(SubCounty),
         SubCounty = fct_reorder(SubCounty, total)
         #SubCounty = fct_lump(SubCounty, 8, w = total)
         ) %>% 
  ggplot(aes(x = SubCounty, y = total))+
  geom_col()+
  scale_y_log10(label = scales::comma_format())+
  coord_flip()+
  labs(y = "Total farming Households")+
  theme_bw()

sub_cir <- crops %>% 
  rowwise() %>% 
  mutate(total = sum(across(where(is.numeric)), na.rm = T)) %>% 
  ungroup() %>% 
  select(SubCounty, total) %>% 
  arrange(-total) %>% 
  mutate(percent = total / sum(total),
         ymax = cumsum(percent),
         ymin = lag(ymax, default = 0),
         labelp = (ymin + ymax) / 2) %>%
  ggplot()+
  geom_rect(aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=SubCounty), show.legend = F)+
  scale_fill_grey()+
  annotate("text", x = 1, y = 0.5,label = "♥\nKENYA\n50%", size = 7)+
  coord_polar(theta="y")+
  xlim(c(1, 4)) +
  theme_void()+
  theme(plot.margin =unit(c(0,0,0,0), "cm"),
        panel.spacing = unit(c(0, 0, 0, 0), "cm"))



farm_dis <- crops %>% 
  pivot_longer(Farming:`Khat (Miraa)`, names_to = "crop", values_to = "value") %>% 
  group_by(crop) %>% 
  summarise(total = sum(value, na.rm = T)) %>% 
  ungroup() %>% 
  mutate(crop = as.factor(crop),
         crop = fct_reorder(crop, total)) %>% 
  ggplot(aes(x = crop, y = total))+
  geom_col()+
  scale_y_continuous(label = scales::comma_format())+
  coord_flip()+
  labs(x = "Crop",
       y = "Total farming Households")+
  theme_bw()

farm_cir <- crops %>% 
  pivot_longer(Farming:`Khat (Miraa)`, names_to = "crop", values_to = "value") %>% 
  group_by(crop) %>% 
  summarise(total = sum(value, na.rm = T)) %>% 
  ungroup() %>% 
  mutate(crop = as.factor(crop),
         crop = fct_reorder(crop, total)) %>% 
  arrange(-total) %>% 
  mutate(percent = total / sum(total),
         ymax = cumsum(percent),
         ymin = lag(ymax, default = 0),
         labelp = (ymin + ymax) / 2) %>% 
  ggplot()+
  geom_rect(aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=crop), show.legend = F)+
  scale_fill_grey(start = 1,end = 0.5,)+
  annotate("text", x = 1, y = 0.5,label = "Farming\n65.3%", size = 7)+
  coord_polar(theta="y")+
  xlim(c(1, 4)) +
  theme_void()+
  theme(plot.margin =unit(c(0,0,0,0), "cm"),
        panel.spacing = unit(c(0, 0, 0, 0), "cm"))

```

```{r grid}
(sub_dis | farm_dis) /
  (sub_cir| plot_spacer()|farm_cir)+
  plot_layout()+
  plot_annotation(title = "	Kenya Census",
                  caption = "@CPXOPZ",
                  theme = theme(plot.title = element_text(size = 22,
                                                          hjust = 0.5,
                                                          face = "bold")))

ggsave(here::here("2021/20210119-W03-Kenya Census", "20210119-W03-Kenya_Census.png"),
       width = 26,
       height = 26,
       units = "cm",
       dpi = "retina",
       type = "cairo")
```

