---
title: "20210105-W02-Transit Cost Project"
author: "CPXOPZ"
date: "2021/1/5"
output: html_document
editor_options: 
  chunk_output_type: console
---

[Data](https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-01-05)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r packages, message=FALSE}
library(dplyr)
library(ggplot2)
library(viridis)
library(patchwork)
```

```{r data, message=FALSE, echo=FALSE}
tuesdata <- tidytuesdayR::tt_load('2021-01-05')
tuesdata <- tidytuesdayR::tt_load(2021, week = 2)

transit_cost <- tuesdata$transit_cost

# transit_cost <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-05/transit_cost.csv')
```

```{r datapre}
skimr::skim(transit_cost)

transit_cost %>% 
  filter(country == 'CN') %>% 
  skimr::skim()

cities <- transit_cost %>% 
  filter(country == 'CN') %>% 
  count(city, sort = T) %>% 
  filter(n >= 10) %>% 
  pull(city)
```

In China, the data included 28 cities

```{r plot}
bar <- transit_cost %>% 
  filter(city %in% cities) %>% 
  mutate(real_cost = as.numeric(real_cost)) %>% 
  group_by(city) %>% 
  summarise(totalcost = sum(real_cost), .groups = "drop") %>% 
  arrange(desc(totalcost)) %>% 
  ggplot(aes(x = city, y = totalcost, fill = city))+
  geom_bar(stat = "identity", show.legend = F)+
  scale_fill_viridis(discrete = T)+
  scale_y_continuous(labels = scales::dollar_format(prefix = "\u00a5"))+
  labs(title = "Cost per city",
       x = "",
       y = "Total Cost(RMB)")+
  theme_bw()

dot <- transit_cost %>% 
  filter(city %in% cities) %>% 
  mutate(real_cost = as.numeric(real_cost)) %>% 
  ggplot(aes(length, real_cost))+
  geom_point(aes(color = city, size = cost_km_millions),alpha = 0.65)+
  scale_color_viridis(discrete = T, guide = F)+
  scale_y_continuous(labels = scales::dollar_format(prefix = "\u00a5"))+
  labs(title = "Cost per project",
       x = "Length(Km)",
       y = "Real cost(RMB)",
       size = "Cost/km in millions of USD",
       caption = "@CPXOPZ\n#TidyTuesday")+
  theme_bw()+
  theme(legend.position = "bottom")

bar / dot +
  plot_annotation(title = "Transit Costs in China",
                  theme = theme(plot.title = element_text(hjust = 0.5,
                                                          face = "bold",
                                                          size = 23)))

ggsave(here::here("2021/20210105-W01-Transit Cost Project", "20210105-W01-Transit_Cost_Project.png"),
       width = 22,
       height = 25,
       units = "cm",
       dpi = "retina",
       type = "cairo")

library(plotly)

ggplotly(dot)



# 环形图，不合适
transit_cost %>% 
  filter(city %in% cities) %>% 
  group_by(city) %>% 
  summarise(totalcost = sum(cost)) %>% 
  mutate(percent = totalcost / sum(totalcost),
         ymax = cumsum(percent),
         ymin = lag(ymax, default = 0),
         label_p = (ymax + ymin) / 2,
         label = glue::glue("{city}-{percent}")) %>% 
  ggplot( aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=city)) +
  geom_rect() +
  # geom_text( x=2, aes(y=label_p, label=label), size=6) + 
  coord_polar(theta="y") +
  xlim(c(-1, 4)) +
  theme_void() +
  theme(legend.position = "none")
```

***

```{r session}
sessionInfo()
```