---
title: "20210323-W13-UN Votes"
author: "CPXOPZ"
date: "2021/3/23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(dplyr)
library(ggplot2)
# remotes::install_github("davidsjoberg/ggstream")
library(ggstream)
library()
library(patchwork)
```

```{r data}
# tuesdata <- tidytuesdayR::tt_load('2021-03-23')
# tuesdata <- tidytuesdayR::tt_load(2021, week = 13)
# 
# unvotes <- tuesdata$unvotes

# Or read in the data manually

unvotes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-23/unvotes.csv')
roll_calls <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-23/roll_calls.csv')
issues <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-23/issues.csv')

# save.image(here::here("2021/20210323-W13-UN Votes", "20210323-W13-UN_Votes.RData"))
```

```{r data prepare}
china <- unvotes %>% 
  left_join(roll_calls, by = "rcid") %>% 
  left_join(issues, by = "rcid") %>% 
  filter(country == "China") %>% 
  mutate(vote = factor(vote, levels = c("yes", "abstain", "no"), labels = c("Yes", "Abstain", "No")))

china_votes <- china %>% 
  group_by(vote, issue) %>% 
  count() %>% 
  tidyr::drop_na(issue)

```

```{r plot}

streamplot <- china %>% 
  mutate(year = lubridate::year(date)) %>% 
  count(year, vote) %>% 
  ggplot(aes(year, n, fill = vote))+
  geom_stream(show.legend = F)+
  geom_stream_label(aes(label = vote), size = 5, fontface = "bold")+
  scale_fill_brewer(palette ="Set1")+
  labs(title = "Vote results over time",
       x = NULL,
       y = NULL)+
  theme_minimal()+
  theme(panel.grid = element_blank(),
        axis.text.y = element_blank())

un <- here::here("2021/20210323-W13-UN Votes", "UN.png")
guoqi <- here::here("2021/20210323-W13-UN Votes", "GUOQI1024.png")
un.logo <- png::readPNG(un, native = TRUE)
guoqi.logo <- png::readPNG(guoqi, native = TRUE)
streamplot <- 
streamplot + inset_element(un.logo, 0.65, 0.85, 0.8, 1)+
  inset_element(guoqi.logo, 0.45, 0.85, 0.6, 1)

dis_plot <- china_votes %>% 
  # filter(vote == "")
  ggplot(aes(forcats::fct_rev(vote), n, fill = issue))+
  geom_col(position = "fill")+
  coord_flip()+
  scale_y_continuous(labels = scales::percent_format(), expand = c(0,0.04))+
  scale_fill_brewer(palette = "Dark2")+
  labs(title = "Issues Distuibution",
       x = NULL,
       y = NULL,
       fill = NULL)+
  theme_minimal()+
  guides(fill = guide_legend(reverse = TRUE,
                             label.position = "top",
                             byrow = TRUE,
                             keyheight = 0.4))+
  theme(legend.position = "bottom")
  
streamplot / dis_plot+
  plot_layout(heights = c(1,0.3))+
  plot_annotation(title = "UN Votes of China",
                  caption = "@CPXOPZ",
                  theme = theme(plot.title = element_text(size = 25,face = "bold", hjust = 0.5, margin = margin(15,5,10,5))))

ggsave(here::here("2021/20210323-W13-UN Votes", "20210323-W13-UN_Votes.png"),
       device = ragg::agg_png(width = 8, height = 8, units = "in", res = 200))

```

